import "~/styles/globals.css";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProviderWrapper } from "./SessionProviderWrapper";
import Header from "./_components/header/Header";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex justify-center w-screen">
        <SessionProviderWrapper>
          <TRPCReactProvider cookies={cookies().toString()}>
            <main className="flex flex-col grow max-w-5xl">
              <Header />
              {children}
            </main>
          </TRPCReactProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
