import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProviderWrapper } from "./SessionProviderWrapper";
import Navbar from "./_components/nav/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <SessionProviderWrapper>
          <TRPCReactProvider cookies={cookies().toString()}>
            <main>
              <Navbar />
            </main>
            {children}
          </TRPCReactProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
