import type { Category } from "~/types";

export const categories: Category[] = [
  {
    name: "Mat",
    match: [
      { name: "Maxi Ica Storm Solna Solna" },
      { name: "Ica Söderberga Vällingby" },
      { name: "Ica Bromma Bromma" },
      { name: "Ica Kvantum Solna Solna" },
      { name: "Ica Kvantum Mall Of Solna" },
      { name: "Ica Lappis Stockholm" },
      { name: "Ica Nära Trångsund Trångsund" },
      { name: "K*City Gross" },
      { name: "City Gross Ab Hassleholm" },
      { name: "City Gross Ab Häggvik" },
      { name: "City Gross Ab Bromma" },
      { name: "Coop Centralen Stockholm" },
      { name: "Coop Vallingby Centrum Vallingby" },
      { name: "Coop Forum Bromma Bromma" },
      { name: "Stora Coop Sundby Park Sundbyberg" },
      { name: "Coop Norra Djurgardsst Stockholm" },
      { name: "Hemkop Odenplan Stockholm" },
      { name: "Hemkop Stockholm Angby Bromma" },
      { name: "Hemkop Vallingby Vallingby" },
      { name: "Lidl 271 / Danderyd St Stocksund" },
      { name: "Lidl 301 / Sthlm Lilje Stockholm" },
      { name: "Lidl 355/Lidingo Torsv" },
      { name: "Lidl 312 / Sollentuna" },
      { name: "Willys Taby Centrum" },
      { name: "Willys Fridhemsplan St Stockholm" },
      { name: "Willys Esplanaden Sund Sundbyberg" },
      { name: "Willys Stockholm Vinst Vallingby" },
    ],
  },
  {
    name: "Apotek",
    match: [
      { name: "K*Apohem Ab" },
      { name: "K*Apotea Ab " },
      { name: "Cura Apoteket Solna" },
      { name: "Apotek Hjärtat Solna Solna" },
      { name: "Apotek Hjärtat Stock Stockholm" },
      { name: "K*Apotek Hja" },
      { name: "K*Apotekhjar" },
      { name: "K*Apoteket A" },
      { name: "Kronans Apotek Stockholm" },
      { name: "Kronans Apotek" },
      { name: "Lloydsapotek Centralst Stockholm" },
    ],
  },
  {
    name: "Räkningar",
    match: [
      { name: "Ellevio Ab" },
      { name: "Vattenfall Ab" },
      { name: "Avgift bankkort" },
      { name: "Hyra" },
    ],
  },
  {
    name: "Transport",
    match: [
      { name: "Nets Apcoa Flow" },
      { name: "Swish Easypark Abeasypark Ab" },
      { name: "Mobilpark Aimo" },
      { name: "Okq8" },
      { name: "Swish Sj Ab" },
      { name: "E-Handel Sl.Se" },
      { name: "St1 Alby" },
      { name: "Swish Ab Storstockholms Lokaltrafik Ab Stockholms Lokaltrafik" },
      { name: "Swish Ab Storstockholms Lokaltrafik" },
    ],
  },
  { name: "Alkohol", match: [{ name: "Systembolaget" }] },
] as const;
